core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from rest_framework import permissions

from rest_framework_simplejwt.views import (
    TokenRefreshView,
)

from apps.api.views import MyTokenObtainPairView  


schema_view = get_schema_view(
    openapi.Info(
        title="Engage Hub API",
        default_version='v1',
        description="API para gerenciamento de eventos do Engage Hub",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contato@engagehub.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
    authentication_classes=[],  # Removido se não necessário
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('contas.urls')),
    path('', include('pages.urls')),
    path('estatisticas/', include('estatisticas.urls')), 
    
    path('api/v1/', include('api.urls')),
    
     # Endpoints JWT personalizados
    path('api/v1/token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
     # Rotas para a documentação Swagger
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/pages/forms.py
from django import forms
from pages.models import Evento, Categoria, Subcategoria

class EventoForm(forms.ModelForm):
    problema = forms.CharField(
        label='Qual o problema?',
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Descreva o problema'})
    )
    
    endereco = forms.CharField(
        label='Qual o endereço da ocorrência:',
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Informe o endereço'})
    )
    latitude = forms.CharField(
        label='Lat:',
        required=True,
        widget=forms.TextInput(attrs={'readonly': 'readonly'})
    )
    longitude = forms.CharField(
        label='Long:',
        required=True,
        widget=forms.TextInput(attrs={'readonly': 'readonly'})
    )
    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.filter(dataFim__isnull=True),
        empty_label="Selecione...",
        label="Categoria",
        required=True,
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    subcategoria = forms.ModelChoiceField(
        queryset=Subcategoria.objects.filter(dataFim__isnull=True),
        empty_label="Selecione...",
        label="Subcategoria",
        required=True,
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    file = forms.FileField(
        label='Insira uma foto:',
        required=True,
        widget=forms.ClearableFileInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Evento
        fields = ['problema', 'endereco', 'latitude', 'longitude', 'categoria', 'subcategoria', 'file']

apps/pages/templates/cadastro_evento.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/map.css' %}">
<!-- Load Leaflet from CDN -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" crossorigin="" />
<script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js" crossorigin=""></script>

<!-- Load Esri Leaflet from CDN -->
<script src="https://unpkg.com/esri-leaflet@^3.0.9/dist/esri-leaflet.js"></script>
<script src="https://unpkg.com/esri-leaflet-vector@4.0.0/dist/esri-leaflet-vector.js"></script>

<!-- Load Esri Leaflet Geocoder from CDN -->
<link rel="stylesheet" href="https://unpkg.com/esri-leaflet-geocoder@^3.1.3/dist/esri-leaflet-geocoder.css">
<script src="https://unpkg.com/esri-leaflet-geocoder@^3.1.3/dist/esri-leaflet-geocoder.js"></script>

<div class="container-fluid" id="form-cadastro-evento">
    <form method="POST" enctype='multipart/form-data' action="{% url 'cadastro_evento' %}">
        {% csrf_token %}
        <div class="container mt-2" id="form_cad_evento">
            <h5>PUBLIQUE SUA DEMANDA</h5>

            <!-- Problema Field -->
            {{ form.problema.label_tag }}
            {{ form.problema }}
            {% for error in form.problema.errors %}
            <div class="important">
                {{ error }}
            </div>
            {% endfor %}
            <br>

            <!-- Endereço Field -->
            {{ form.endereco.label_tag }}
            {{ form.endereco }}
            <div id="endereco-suggestions"></div>
            {% for error in form.endereco.errors %}
            <div class="important">
                {{ error }}
            </div>
            {% endfor %}
            <br>

            <!-- Latitude and Longitude (hidden) -->
            <div class="d-none">
                {{ form.latitude.label_tag }}
                {{ form.latitude }}
    
                {{ form.longitude.label_tag }}
                {{ form.longitude }}
            </div>
        </div>

        <br>

        <!-- Map (if applicable) -->
        <div id="map" class="container"></div>

        <br>

        <!-- Campo de Categoria -->
        <div class="container">
            {{ form.categoria.label_tag }}
            {{ form.categoria }}
            {% for error in form.categoria.errors %}
            <div class="important">{{ error }}</div>
            {% endfor %}
        </div>

        <br>

        <!-- Campo de Subcategoria, que será carregado dinamicamente via AJAX -->
        <div class="container" id="showSubcategorias">
            <!-- O conteúdo carregado pelo AJAX aparecerá aqui -->
        </div>
        <br>

        <!-- File Upload -->
        <div class="container">
            <div class="mb-4">
                {{ form.file.label_tag }}
                {{ form.file }}
                {% for error in form.file.errors %}
                <div class="important">
                    {{ error }}
                </div>
                {% endfor %}
            </div>
        </div>

        <!-- Submit and Back Buttons -->
        <div class="d-flex justify-content-end mb-3 px-3">
            <button type="submit" class="btn btn-primary btn-sm me-2">
                <i class="bi bi-pencil-square"></i> Publicar
            </button>
            <button type="button" class="btn btn-danger btn-sm" onclick="window.location.href='{% url 'home' %}';">
                <i class="bi bi-arrow-left-circle"></i> Voltar
            </button>
        </div>
    </form>
</div>

{% block scripts %}
    <script src="{% static 'js/map.js' %}"></script> <!-- Carrega o arquivo map.js corretamente -->
{% endblock %}

<!-- Função para carregar subcategorias dinamicamente -->
<script type="text/javascript">
    $(document).ready(function () {
        $('#id_categoria').change(function () {  // Certifique-se de que o id do campo categoria está correto
            var categoria_id = $(this).val();  // Pega o valor da categoria selecionada
    
            if (categoria_id) {
                $.ajax({
                    url: "{% url 'load_subcategorias' %}",  // URL correta da view
                    type: 'POST',
                    data: {
                        id_categoria: categoria_id,
                        csrfmiddlewaretoken: $('[name="csrfmiddlewaretoken"]').val()  // Inclui o token CSRF
                    },
                    success: function (response) {
                        // Carrega o conteúdo de subcategorias no HTML
                        $('#showSubcategorias').html(response.htmlresponse);
                    }
                });
            } else {
                // Limpa o campo de subcategorias se nenhuma categoria for selecionada
                $('#showSubcategorias').html('<p>Selecione uma categoria primeiro</p>');
            }
        });
    }); 

    let enderecoInput = document.getElementById('id_endereco'); 
    let suggestionsDiv = document.getElementById('endereco-suggestions');

    enderecoInput.addEventListener("input", function () {
        const address = enderecoInput.value;

        if (address.length >= 5) {
            fetchSuggestions(address);
        } else {
            suggestionsDiv.innerHTML = '';
        }
    });

    enderecoInput.addEventListener("keydown", function (event) {
        if (event.key === "Enter") {
            event.preventDefault();
            const selectedSuggestion = suggestionsDiv.querySelector('.suggestion.selected');
            if (selectedSuggestion) {
                selectSuggestion(JSON.parse(selectedSuggestion.getAttribute('data-suggestion')));
            }
        }
    });

    function fetchSuggestions(address) {
        const url = 'https://nominatim.openstreetmap.org/search.php?q=' + address + '&dedupe=0&addressdetails=1&format=jsonv2';

        fetch(url)
            .then(response => response.json())
            .then(data => {
                suggestionsDiv.innerHTML = '';

                data.forEach(item => {
                    let endereco = (item.address.road ? item.address.road : "")
                        + ", " + (item.address.house_number ? item.address.house_number : "S/N")
                        + ", " + (item.address.suburb ? item.address.suburb : "")
                        + ", " + (item.address.city ? item.address.city : "")
                        + " - " + (item.address.state ? item.address.state : "")
                        + ", " + (item.address.postcode ? item.address.postcode : "")
                        + ", " + (item.address.country ? item.address.country : "");

                    const suggestion = document.createElement('div');
                    suggestion.className = 'suggestion';
                    suggestion.textContent = endereco;
                    suggestion.setAttribute('data-suggestion', JSON.stringify(item));
                    suggestion.addEventListener('click', () => {
                        selectSuggestion(item, endereco);
                    });
                    suggestionsDiv.appendChild(suggestion);
                });
            })
            .catch(error => {
                console.error(error);
            });
    }

    function selectSuggestion(item, endereco) {
        const lat = item.lat;
        const lng = item.lon;
        document.getElementById('id_latitude').value = lat; // Certifique-se de usar o ID correto
        document.getElementById('id_longitude').value = lng; // Certifique-se de usar o ID correto
        document.getElementById('id_endereco').value = endereco;
        document.getElementById('id_bairro').value = item.address.suburb;
        map.setView([lat, lng], 15);
        marker = L.marker([lat, lng]);
        adicionarMarcador(marker);
        suggestionsDiv.innerHTML = '';
    }
</script>

{% endblock content %}

apps/pages/templates/filtraEventos.html
{% extends 'base.html' %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/gov_style.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% block content %}

<script type="text/javascript">
    $(function () {
      $("#userSearch").autocomplete({
        source: function (request, response) {
          $.getJSON("{% url 'user_autocomplete' %}", {
            userSearch: request.term,
          }, function (data) {
            response(data.results);
          });
        },
        minLength: 2,
        select: function (event, ui) {
          $('#userSearch').val(ui.item.value);
          return false;
        }
      });
    });
</script>

<div class="container-fluid">

  <div class="container p-0 mb-1 mt-4">
    <h5 class="titulo-filtra-demandas"> <strong> <i class="bi bi-search"></i> Consultas </strong></h5>
    <hr class="mt-1">
  </div>

  <form action="{% url 'evento_search' %}" method="GET">
    <div class="container main-filtra-eventos">
      <div class="col-3 m-1">
        <label class="form-label m-1"> Pesquisar Demanda: </label>
        <input type="text" name="numOcorrenciaSearch" class="form-control form-control-sm m-1"
          placeholder="Número da Demanda" value="{{ numOcorrenciaSearch|default_if_none:'' }}" />
      </div>

      <div class="col-3 m-1">
        <label class="form-label m-1"> Status: </label>
        <select class="form-select form-select-sm m-1" aria-label="Selecione o status" name="statusSearch">
          <option value="">- Todos - </option>
          {% for eve in listStatus %}
            <option value="{{ eve.id }}" {% if statusSearch == eve.id|stringformat:"s" %}selected{% endif %}>{{ eve.txtStatusEvento }}</option>
          {% endfor %}
        </select>
      </div>

      <div class="col-3 m-1">
        <label class="form-label m-1"> Categoria: </label>
        <select class="form-select form-select-sm m-1" aria-label="Selecione a categoria" name="categoriaSearch">
          <option value="">- Todos - </option>
          {% for cat in listCategoria %}
            <option value="{{ cat.id }}" {% if categoriaSearch == cat.id|stringformat:"s" %}selected{% endif %}>{{ cat.txtCategoria }}</option>
          {% endfor %}
        </select>
      </div>

      <div class="row filtros-button">
        <div class="col-3 m-1">
          <label for="users" class="form-label form-label-sm m-1"> Usuário: </label>
          <input type="text" class="form-control form-control-sm m-1" id="userSearch" name="userSearch"
            placeholder="Pesquise por email do usuário" value="{{ userSearch|default_if_none:'' }}">
        </div>

        <div class="col-3 m-1">
          <label class="form-label m-1"> Início: </label>
          <input type="date" name="dataInicioSearch" class="form-control form-control-sm m-1"
            value="{{ dataInicioSearch|default_if_none:'' }}" />
        </div>

        <div class="col-3 m-1">
          <label class="form-label m-1"> Fim: </label>
          <input type="date" name="dataFimSearch" class="form-control form-control-sm m-1"
            value="{{ dataFimSearch|default_if_none:'' }}" />
        </div>

        <div class="col-3 div-button-filtrar-eventos">
          <button type="submit" class="btn btn-outline-success btn-sm m-1">
            <i class="bi bi-filter-circle"></i> Filtrar </button>
          <button type="reset" class="btn btn-outline-danger btn-sm m-1">
            <i class="bi bi-x-circle"></i> Limpar </button>
        </div>
      </div>
    </div>
  </form>

  {% if listEventoHistoricoSearch %}
  <div class="container mb-1 mt-3">
    <h5> <strong> ENGAGE_HUB - FILTROS </strong></h5>
    <hr class="mt-1">
  </div>

  <div class="container mb-1 mt-3">
    <table class="table table-striped tabela-filtros">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">Usuário</th>
          <th scope="col">Status</th>
          <th scope="col">Categoria</th>
          <th scope="col">Data</th>
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for row in listEventoHistoricoSearch %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ row.idEvento.idUsuario.get_full_name }}</td>
          <td>{{ row.idStatusEvento.txtStatusEvento }}</td>
          <td>{{ row.idEvento.idSubcategoria.idCategoria.txtCategoria }}</td>
          <td>{{ row.idEvento.dataInicio|date:"d/m/Y H:i" }}</td>
          <td>
            <button type="button" class="btn btn-danger btn-sm"
              onclick="window.location.href='{% url 'selecionarEvento' num_ocorrencia=row.idEvento.numOcorrencia %}';"><i
              class="bi bi-arrow-left-circle"></i> Acessar
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <!-- Pagination Links-->
    <div class="container pagination">
      <nav aria-label="Page navigation">
        <ul class="pagination">
          {% if listEventoHistoricoSearch.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ listEventoHistoricoSearch.previous_page_number }}">Anterior</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">Anterior</span>
            </li>
          {% endif %}

          <!-- Display page numbers -->
          {% for page_num in listEventoHistoricoSearch.paginator.page_range %}
            {% if page_num == listEventoHistoricoSearch.number %}
              <li class="page-item active">
                <span class="page-link">{{ page_num }}</span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_num }}">{{ page_num }}</a>
              </li>
            {% endif %}
          {% endfor %}

          {% if listEventoHistoricoSearch.has_next %}
            <li class="page-item">
              <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ listEventoHistoricoSearch.next_page_number }}">Próxima</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">Próxima</span>
            </li>
          {% endif %}
        </ul>
      </nav>
      <!-- <div class="button-voltar">
        <button type="button" class="btn btn-danger btn-sm"
          onclick="window.location.href='{% url 'homeGoverno' %}';"><i class="bi bi-arrow-left-circle"></i> Voltar
        </button>
      </div> -->
    </div>
  </div>
  {% endif %}
</div>

{% endblock %}

apps/pages/templates/home.html
{% extends 'base.html' %}
{% block title %}Engage Hub{% endblock %}

{% block content %}

<style>
    a.text-muted:hover {
        color: #0d6efd !important; 
    }
</style>

<main class="container-fluid">
    <div class="container mt-3">
        <div class="row">
            <div class="col-12">
                <h1 class="display-5 text-center">Bem-vindo ao Engage Hub</h1>
                <p class="lead text-center">Aqui você pode ajudar a sua cidade a se tornar um lugar melhor!</p>
            </div>
        </div>
    <div class="d-grid gap-2 col-12 mx-auto mt- mb-3 justify-content-center botao_demanda">
        <a class="btn btn-primary me-md-2" href="{% url 'iniciar' %}" type="submit">
            <i class="fas fa-plus-circle me-2"></i> Como você quer ajudar sua cidade?
        </a>
    </div>

    {% for eventoHistorico in listHistoricoEvento %}
        <div class="container d-flex justify-content-center">
            <div class="card mb-3 mt-2" style="max-width: 30rem;">
                <div class="card-header">
                    <div class="row align-items-center">
                        <!-- Coluna da esquerda: Ícone e nome do usuário -->
                        <div class="col-auto d-flex align-items-center">
                            <i class="fas fa-user-circle fs-2 text-secondary me-2"></i>
                            <p class="fw-semibold mb-0">{{ eventoHistorico.idEvento.idUsuario.get_full_name }}</p>
                        </div>
                        <!-- Coluna da direita: Tempo decorrido -->
                        <div class="col text-end">
                            <p class="fw-medium mb-0 text-muted">há {{ eventoHistorico.tempo_decorrido }} minutos</p>
                        </div>
                    </div>
                </div>
                <img src="data:image/jpeg;base64,{{ eventoHistorico.idEvento.fileBase64 }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <p class="card-text">{{ eventoHistorico.idEvento.txtProblema }}.</p>
                </div>
                <div class="card-footer text-end">
                    <a href="{% url 'selecionarEvento' eventoHistorico.idEvento.numOcorrencia %}" class="text-decoration-none text-muted">Visualizar Demanda</a>
                </div>
                
            </div>
        </div>
    {% endfor %}

    <!-- Paginação -->
    {% if listHistoricoEvento.has_other_pages %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center mt-4">

                {% if listHistoricoEvento.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ listHistoricoEvento.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </span>
                    </li>
                {% endif %}

                {% for num in listHistoricoEvento.paginator.page_range %}
                    {% if listHistoricoEvento.number == num %}
                        <li class="page-item active">
                            <span class="page-link">{{ num }} <span class="sr-only">(atual)</span></span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if listHistoricoEvento.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ listHistoricoEvento.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </span>
                    </li>
                {% endif %}

            </ul>
        </nav>
    {% endif %}

</main>

{% endblock %}

apps/pages/templates/homeGoverno.html
{% extends 'base.html' %}
{% block content %}


  <!-- Cards com as contagens -->
  <div class="container-fluid">
    <div class="row gx-3">
      <div class="col">
        <div class="card mb-2 border-primary">
          <div class="card-body">
            <h6 class="card-title" style="font-size: smaller;">Demandas Totais</h6>
            <span class="badge bg-primary"> {{ contTotal }} </span>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-2 border-success">
          <div class="card-body">
            <h6 class="card-title" style="font-size: smaller;">Demandas Finalizadas</h6>
            <span class="badge bg-success"> {{ contFinalizada }} </span>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-2 border-danger">
          <div class="card-body">
            <h6 class="card-title" style="font-size: smaller;">Aguardando</h6>
            <span class="badge bg-danger"> {{ contAguardando }} </span>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-2 border-warning">
          <div class="card-body">
            <h6 class="card-title" style="font-size: smaller;">Em andamento</h6>
            <span class="badge bg-warning"> {{ contEmAndamento }} </span>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Título e notificações -->
  <div class="container titulo_gestor_demandas">
    <h6 class="titulo_texto_gestor_demandas"> GESTOR DE DEMANDAS MUNICIPAIS</h6>
    <div class="div-notificacoes">
      <i class="bi bi-bell-fill"></i>
      <span class="titulo_notificacoes"> NOTIFICAÇÕES </span>
      <span class="badge bg-danger">{{ contAguardando }}</span>
    </div>
  </div>

  <!-- Mapa -->
  <div class="container-fluid">
    {{ mapHtml|safe }}
  </div>

 <!-- Formulário de Pesquisa -->
<div class="pesquisa_demanda">
  <form method="GET" action="{% url 'search' %}">
    <h6 class="form-label"> Pesquisar Ocorrência: </h6>
    <div class="pesquisa_demanda_form">
      <input type="text" id="numOcorrencia" name="numOcorrencia" class="form-control" placeholder="Número da Ocorrência" />
      <button type="submit" class="btn btn-primary btn_pesquisa_demanda">
        <i class="bi bi-search icone-pesquisa-demanda-sm"></i>
        Pesquisar
      </button>
      <button class="btn btn-primary btn-lista-demandas" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
        <i class="bi bi-card-list"></i>Demandas
      </button>
    </div>
  </form>
</div>

 <!-- Off Canvas -->
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <h5 id="offcanvasRightLabel"> Últimas Demandas</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
		{% for eventoHistorico in listHistoricoEventoDireita %}
		<div class="container-fluid d-flex justify-content-center">
			<div class="card mb-2 mt-2" style="max-width: 100%;">
				<div class="card-header py-2">
					<div class="row align-items-center">
						<!-- Ícone e nome do usuário -->
						<div class="col-auto d-flex align-items-center">
							<i class="fas fa-user-circle fs-3 text-secondary me-2"></i>
							<p class="fw-semibold mb-0 fs-7">{{ eventoHistorico.idEvento.idUsuario.get_full_name }}</p>
						</div>
						<!-- Tempo decorrido -->
						<div class="col text-end">
							<p class="fw-medium mb-0 text-muted small">há {{ eventoHistorico.tempo_decorrido }} minutos</p>
						</div>
					</div>
				</div>
				{% if eventoHistorico.idEvento.fileBase64 %}
					<div class="text-center">
						<img src="data:image/jpeg;base64,{{ eventoHistorico.idEvento.fileBase64 }}" class="img-fluid rounded" alt="Imagem do evento">
					</div>
				{% endif %}
				<div class="card-body py-2">
					<p class="card-text mb-1 small">{{ eventoHistorico.idEvento.txtProblema }}</p>
					
				</div>
				<div class="card-footer text-end py-2">
					<a href="{% url 'selecionarEvento' eventoHistorico.idEvento.numOcorrencia %}" class="text-decoration-none small">
						Visualizar Demanda
					</a>
				</div>
			</div>
		</div>
		{% endfor %}
    </div>
</div>


{% endblock %}

apps/pages/templates/subcategoriaAjax.html
<div class="form-group">
    <label for="id_subcategoria">Subcategoria</label>
    <select name="subcategoria" id="id_subcategoria" class="form-select">
        <option value="">Selecione...</option>
        {% for subcategoria in subcategorias %}
            <option value="{{ subcategoria.id }}">{{ subcategoria.txtSubcategoria }}</option>
        {% endfor %}
    </select>
</div>